"""Compare text-to-image models visually.

Upload a CSV of prompts and get a side by side eval of image generated by a set of models.
Running againts additional prompts updates the same eval, backed by a versioned dataset.
"""

from mixtrain import Dataset, Eval, File, MixFlow, Model, Image

prompt_col = "prompt"


def verify_eval(models: list[str], eval_name: str) -> bool:
    """Ensure the Eval schema matches the requested models.

    An Eval compares a fixed set of models, so a run that requests a different
    set of models can't be added to existing Eval.

    Returns True if the eval exists False otherwise. Schema mismatch raises.
    """

    if not Eval.exists(eval_name):
        return False

    expected_schema = [prompt_col, *models]
    current_schema = Dataset(f"{eval_name}-results").schema.names

    if sorted(current_schema) != sorted(expected_schema):
        raise ValueError(
            f"'Eval schema mismatch: {eval_name}' current schema {', '.join(current_schema)}, "
            f"doesn't match the requested models{', '.join(models)}. "
            f"Correct the eval name to add more eval prompts to existing comparison "
            f"or provide a new eval_name to create a new comparison."
        )

    return True


def generate(source: Dataset, model_names: list[str]) -> Dataset:
    """Generate every prompt on every model, one image column per model."""
    generated = None
    image_columns = {}
    for model in model_names:
        images = Model.batch([model], source, input_columns=[prompt_col])
        # Keep the image and drop the rest
        images = images.sql(
            f'SELECT {prompt_col}, image AS "{model}" FROM data'
        ).with_column_types({model: Image})
        # A full outer join keeps a prompt even if one model failed on it.
        generated = (
            images
            if generated is None
            else generated.join(images, prompt_col, "full outer")
        )

    return generated


class CompareImageModels(MixFlow):
    """Compare text-to-image models on your prompts"""

    def run(
        self,
        prompts: File | None = None,
        models: list[Model] = [Model("flux-2-flex"), Model("qwen-image")],
        eval_name: str = "image-gen-eval",
    ) -> dict:
        """Generate every prompt on every model.

        Args:
            prompts: CSV with a `prompt` column. Leave empty to use the
                prompts that ship with this example.
            models: The text-to-image models to compare.
            eval_name: Name of the eval. Will be created if not existing.
        """
        model_names = [model.name for model in models]
        existing = verify_eval(model_names, eval_name)

        path = prompts.to_file() if prompts else "prompts.csv"
        prompt_dataset = Dataset.from_file(path)

        results = generate(prompt_dataset, model_names)

        result_dataset_name = f"{eval_name}-results"
        if existing:
            result_dataset = Dataset(result_dataset_name).append(results)
            eval = Eval(eval_name)
        else:
            result_dataset = results.save(result_dataset_name)
            eval = Eval.from_dataset(
                result_dataset,
                name=eval_name,
                columns=[prompt_col, *model_names],
                description=f"Image gen eval for {', '.join(model_names)}",
            )
        return {
            "evaluation": eval,
            "results": result_dataset,
        }
